/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package devcup.search4u.gui;

import devcup.search4u.common.LogLevel;
import java.io.IOException;
import javax.swing.text.BadLocationException;
import javax.swing.text.html.HTMLDocument;

/**
 *
 * @author whiord
 */
public class JournalFrame extends javax.swing.JFrame {
    static JournalFrame instance;
        
    public static JournalFrame getInstance(){
        if (instance == null){
            instance = new JournalFrame();
        }
        return instance;
    }
    /**
     * Creates new form JournalFrame
     */
    private JournalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeJournalButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        journalPane = new javax.swing.JTextPane();

        closeJournalButton.setLabel("Закрыть");
        closeJournalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeJournalButtonMouseClicked(evt);
            }
        });

        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        journalPane.setContentType("text/html"); // NOI18N
        journalPane.setText("<html>\n<head>\n\n<style type=\"text/css\">\n.info{\ncolor:#0036B5;\n}\n.debug{\ncolor:#00701E;\n}\n.error{\ncolor:#AD022A;\n}\n</head>\n</style>\n<body id=\"body\"></body>\n<html>\n");
        journalPane.setMaximumSize(new java.awt.Dimension(800, 2147483647));
        jScrollPane4.setViewportView(journalPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                    .addComponent(closeJournalButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeJournalButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeJournalButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeJournalButtonMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_closeJournalButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JournalFrame().setVisible(true);
            }
        });
    }

    public void logWork(LogLevel level, String message) {
        HTMLDocument doc = (HTMLDocument) journalPane.getDocument();
        try { 
            doc.insertBeforeEnd(doc.getElement("body"), level.decorateHTML(message));
        } catch (BadLocationException ex) {
            
        } catch (IOException ex) {
            System.out.println("Exception");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeJournalButton;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane journalPane;
    // End of variables declaration//GEN-END:variables
}
